language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - APP_ENV=testing

before_install:
  - composer self-update

install:
  - composer install --dev
  - php -r "copy('app/config/app.default.php', 'app/config/app.php');"
  - npm install

script:
  - npm run-script build
  - phpunit
